server/app-env.js
server/app.constants.js

Clean up the unclear code revolving around removing the legacy config file.

Remove legacy config migration tool

---

client-vue/src/App.vue
client-vue/src/backend/base.service.ts
client-vue/src/backend/index.ts
client-vue/src/backend/printer-files.service.ts
client-vue/src/components/FileList.vue
client-vue/src/components/PrinterDetails.vue
client-vue/src/models/api/status-response.model.ts
client-vue/src/models/printers/file-list.model.ts
client-vue/src/models/printers/printer-file.model.ts
client-vue/src/store/printers/printers.actions.ts
client-vue/src/store/printers/printers.state.ts
server/constants/service.constants.js
server/controllers/printer-file.controller.js
server/controllers/validation/printer-files-controller.validation.js
server/exceptions/exception.handler.js
server/services/octoprint/constants/octoprint-service.constants.js
server/services/octoprint/octoprint-api.service.js
server/services/octoprint/utils/api.utils.js
server/services/printer-files.service.js
server/state/data/file.cache.js
server/state/files.store.js

Improve file sync and file deletion caching and frontend store

---

.github/workflows/codeql-analysis.yml
client-vue/src/backend/printer-files.service.ts
client-vue/src/backend/printers.service.ts
client-vue/src/backend/server.api.ts
client-vue/src/components/Dialogs/BatchJsonCreateDialog.vue
client-vue/src/components/Dialogs/UpdatePrinterDialog.vue
client-vue/src/components/Generic/Actions/PrinterDeleteAction.vue
client-vue/src/components/Generic/Actions/PrinterSettingsAction.vue
client-vue/src/components/Generic/Actions/PrinterUrlAction.vue
client-vue/src/components/Generic/Actions/RefreshFilesAction.vue
client-vue/src/components/PrinterGrid/GridItem.vue
client-vue/src/components/PrinterGrid/PrinterGrid.vue
client-vue/src/components/PrinterList/FileControlList.vue
client-vue/src/components/PrinterList/PrinterDetails.vue
client-vue/src/components/Scheduling/CalendarView.vue
client-vue/src/views/HomePage.vue
client-vue/src/views/Printers.vue
client-vue/src/views/Scheduling.vue
server/controllers/printer-file.controller.js
server/controllers/printer.controller.js
server/controllers/validation/printer-files-controller.validation.js
server/services/octoprint/octoprint-api.service.js
server/services/printer-files.service.js
server/state/files.store.js

 Stop print command

---

.github/workflows/docker_builds.yml
.github/workflows/docker_quick_build.yml
.github/workflows/docker_release.yml
README.md
client-npm/package.json
client-vue/package.json
docker-compose.yml
package-lock.json
package.json

Prerelease fixes, client release and multi-arch docker build

---

server/services/printer.service.js
server/state/printers.store.js
test/api/printer-controller.test.js
test/application/state/printer-store.test.js

Cover printer API

---

package-lock.json
package.json
server/server.core.js

Add helmet

---

client-vue/src/backend/printers.service.ts
client-vue/src/backend/server.api.ts
client-vue/src/components/Generic/Dialogs/UpdatePrinterDialog.vue
client-vue/src/models/printers/printer.model.ts
server/controllers/printer.controller.js
test/api/printer-controller.test.js

Expose OP API key with operator or admin role only for printer update

---

client-vue/src/backend/base.service.ts
client-vue/src/backend/printer-group.service.ts
client-vue/src/backend/server.api.ts
client-vue/src/store/printers.state.ts
client-vue/src/views/settings/PrinterGroupsSettings.vue
server/controllers/printer-files.controller.js
server/services/octoprint/octoprint-api.service.js
server/services/printer-group.service.js
server/services/validators/printer-group-service.validation.js
test/api/printer-files-controller.test.js

Add ability to clear printer from group

---

client-npm/package.json
client-vue/package.json
package-lock.json
package.json

Release client 0.1.13 for server 0.0.4-pre1

---

client-vue/src/router/index.ts
client-vue/src/views/Settings.vue
client-vue/src/views/settings/UserManagementSettings.vue
server/controllers/user.controller.js
server/services/authentication/role.service.js
server/services/authentication/user.service.js
server/tasks/boot.task.js
test/api/test-data/create-user.js
test/api/user-controller.test.js
test/application/alert-service.test.js
test/application/user-service.test.js

Basic user management (API)

---

client-vue/package-lock.json
client-vue/package.json
client-vue/src/App.vue
client-vue/src/backend/printer-file.service.ts
client-vue/src/backend/server.api.ts
client-vue/src/backend/user.service.ts
client-vue/src/components/Generic/AlertStack.vue
client-vue/src/components/Generic/Dialogs/CreatePrinterDialog.vue
client-vue/src/components/Generic/Dialogs/UpdatePrinterDialog.vue
client-vue/src/components/Generic/PrintJobsMenu.vue
client-vue/src/components/Generic/SideNavs/FileExplorerSideNav.vue
client-vue/src/event-bus/alert.events.ts
client-vue/src/models/sse-messages/printer-sse-message.model.ts
client-vue/src/models/user.model.ts
client-vue/src/store/uploads.state.ts
client-vue/src/views/Settings.vue
client-vue/src/views/settings/HubSettings.vue
client-vue/src/views/settings/OtherSettings.vue
client-vue/src/views/settings/UserManagementSettings.vue
docker-compose.yml
package-lock.json
package.json
server/services/octoprint/octoprint-api.service.js
server/state/data/file-upload-tracker.cache.js
server/tasks/printer-sse.task.js
server/tasks/printer-test.task.js
test/api/sse-printers.test.js

Fix upload bars and split from info messages

---

README.md
client-npm/package.json
client-vue/package.json
client-vue/src/components/PrinterGrid/PrinterGrid.vue
client-vue/src/constants/printer-grid.constants.ts
client-vue/src/store/printers.state.ts
package-lock.json
package.json
server-nest/yarn.lock

Jep 4 cols * 4 * 4 = 16 * 4 = 64 printers 🚀

Add 4th col to printer group

---

.whitesource
renovate.json

- Configure .whitesource
- Configure renovate

Add configuration for autofixes and package update

---

.github/workflows/docker_quick_build.yml
.github/workflows/docker_release.yml
server/test/api/printer-files-controller.test.js
server/test/application/history-service.test.js
server/test/application/server-commands.test.js
server/test/application/state/history-store.test.js
server/test/application/state/printer-store.test.js

Fix docker build and fix tests

---

.github/workflows/nodejs.yml
.github/workflows/vue-publish.yml
server/package-lock.json
server/package.json

Set fail-fast false nodejs 14 build (not required)

---

server-nest/package.json
server-nest/src/main.ts
server-nest/yarn.lock

Removes EJS related packages in the NestJS project

Removes EJS rendering as this was never intended to be used

---

server/middleware/passport.js
server/package-lock.json
server/package.json
server/server.core.js
server/services/authentication/user-token.service.js
server/test/api/auth-controller.test.js
server/test/domain/user-schema.test.js

Try to sync indexes for user schema - remove remember_me strategy

---

server-nest/.env.development
server-nest/e2e.Dockerfile
server-nest/ormconfig.ts
server-nest/package.json
server-nest/src/main.ts
server-nest/yarn.lock

Give the nest server an upgrade push

---

.github/workflows/docker_quick_build.yml
README.md
client-npm/package.json
client-vue/package.json
client-vue/src/router/index.ts
client-vue/src/views/Settings.vue
client-vue/src/views/settings/FdmSettings.vue
server/package-lock.json
server/package.json

Release new client, prepare 1.0.0 release

---

server/controllers/settings.controller.js
server/index.js
server/models/ServerSettings.js
server/server.env.js
server/test/api/printer-controller.test.js
server/test/api/settings-controller.test.js
server/test/api/sse-printers.test.js
server/test/api/user-controller.test.js

Tests api printer

---

.github/ISSUE_TEMPLATE/bug_report.md
.github/ISSUE_TEMPLATE/developer_report.md
.github/pull_request_template.md
CODE_OF_CONDUCT.md
CONTRIBUTING.md
README.md

See title for added repo root files

Adds templates CODE_OF_CONDUCT.md and CONTRIBUTING.md

---

.github/ISSUE_TEMPLATE/bug_report.md
.github/ISSUE_TEMPLATE/developer_report.md

Please include a summary of the change and which issue is fixed.
Fixes developer report and bug report

Adjust FDM developer and bug report

---

README.md
server/package.json

Small edits in readme before 1.1.1 merge and release

Release v1.1.1 edits

---

client-vue/package-lock.json
client-vue/package.json
server-nest/package.json
server-nest/yarn.lock
server/package-lock.json
server/package.json

Updates slightly outdated packages on all subprojects

Update client, server and server-nest packages

---

server/package-lock.json
server/package.json

Release administration
Server package version update

Update server version to 1.1.2

---

server-nest/package.json
server-nest/yarn.lock

Apply server 1.1.2 version

---

server/package-lock.json
server/package.json

Server `system-information@5.11.5` to `system-information@5.11.6`

Updates server package for system information

---

.github/workflows/docker_release.yml
.github/workflows/nestjs-e2e.yml
.github/workflows/nestjs.yml
.github/workflows/nodejs.yml
.github/workflows/vue-publish.yml

Adjusts the branch names to `main` and `develop`

Name changes branches in GHA workflows

---

client-vue/.eslintrc.js
client-vue/src/components/Generic/PrintJobsMenu.vue
client-vue/src/views/Printers.vue

- Adds a search bar to the printer jobs menu
- Customizes the printers list search bar icon placement

Add printer jobs menu search bar

---

client-npm/package.json
client-vue/package.json
renovate.json
server/package-lock.json
server/package.json

Release client 0.3.9 and server 1.1.5

---

client-npm/package.json
client-vue/package.json
client-vue/src/components/Generic/AlertErrorDialog.vue
client-vue/src/components/Generic/Dialogs/PrinterChecksPanel.vue
client-vue/src/models/sse-messages/printer-sse-message.model.ts
server/constants/state.constants.js
server/handlers/logger.js
server/package-lock.json
server/package.json
server/services/printer.service.js
server/services/validators/printer-service.validation.js
server/state/printer.state.js
server/tasks/printer-test.task.js
server/tasks/printer-websocket.task.js
server/test/api/tasks/websocket-task.test.js
server/test/application/state/printer-store.test.js
server/test/application/test-data/printer.data.js
server/test/definition/state-constant.test.js

Fixes #359 and #358 
Mark printer as invalid when not OctoPrint

Bugfix/359 response undefined not caught (websocket task failures)

---

client-npm/package.json
client-vue/package.json
client-vue/src/components/Generic/Dialogs/CreatePrinterDialog.vue
client-vue/src/components/Generic/Dialogs/UpdatePrinterDialog.vue
server/package-lock.json
server/package.json

Reset test panel on reopening Create/Update printer

---

client-vue/src/backend/printer-file.service.ts
client-vue/src/directives/file-upload.directive.ts
client-vue/src/utils/uploads-state.utils.ts

Validate print flag boolean print upload - fix frontend missing flag

---

client-npm/package.json
client-vue/package.json
client-vue/src/backend/printers.service.ts
client-vue/src/components/Generic/Dialogs/CreatePrinterDialog.vue
client-vue/src/components/Generic/Dialogs/UpdatePrinterDialog.vue
server/controllers/validation/printer-files-controller.validation.js
server/package-lock.json
server/package.json

- Forgot small flag for bugfix 364
- Added frontend copy paste functionality in dialog

Added frontend copy paste functionality in dialog - quick credential copier

---

server/services/server-release.service.js
server/services/server-update.service.js

Reuse previous analysis for log report as well (forgot this earlier)

---

docker-compose.yml
docs/USING_DOCKER.md

Documentation and docker-compose setup fixing #422

Fix docker-compose and docs typos

---

server/middleware/database.js
server/server.core.js
server/server.host.js

Move database state interceptor

---

server/controllers/printer.controller.js
server/test/api/printer-controller.test.js

Fix and test unused OctoPrint reconnect API endpoint

---

server-nest/package.json
server-nest/yarn.lock

[Nest] Updates the node types package

---

client-vue/package.json
client-vue/yarn.lock

Updates some slightly outdated packages (eslint vue plugin)

Update Vue2 router package client

---

client-vue/src/components/Generic/Dialogs/CreatePrinterDialog.vue
client-vue/src/components/Generic/Forms/PrinterCrudForm.vue
client-vue/src/models/client-settings/client-settings.model.ts
client-vue/src/models/server-settings/printer-file-clean-settings.model.ts

Reset form after creating a printer from modal

---

client-npm/package.json
client-npm/scripts/build.ps1
client-npm/scripts/install.ps1
client-npm/scripts/publish.ps1
client-vue/src/components/PrinterGrid/PrinterTile.vue
server/package.json
server/yarn.lock

- Update client to 0.3.16
- Update NPM release scripts to yarn
- Represents the filament color using a border

Change filament color to right border (client 0.3.16)

---

client-vue/src/components/Generic/Dialogs/CreatePrinterDialog.vue
client-vue/src/components/Generic/Dialogs/UpdatePrinterDialog.vue

Fixes that the clipboard API is not always available (IP+non-HTTPS or Firefox)

Workaround for Clipboard not being available

---

client-vue/src/components/Generic/TopBar.vue

Fixes topbar negative time formatting

Fix time in topbar (negative values)

---

client-vue/src/backend/custom-gcode.service.ts
client-vue/src/backend/server.api.ts
client-vue/src/components/Generic/SideNavs/FileExplorerSideNav.vue
client-vue/src/components/PrinterGrid/PrinterTile.vue
server/controllers/custom-gcode.controller.js
server/jest.config.js
server/middleware/printer.js
server/services/octoprint/octoprint-api.routes.js
server/services/octoprint/octoprint-api.service.js
server/state/printers.store.js
server/test/api/custom-gcode-controller.test.js
server/test/extensions.js

Fixes #596 to stop prints more quickly, especially when preheating

Implement emergency stop M112 gcode command

---

client-npm/package.json
client-vue/package.json
server/package.json
server/yarn.lock

Release and install client 0.3.24

---

server/state/files.store.js
server/test/application/state/files-store.test.js

Fix file deletion task and test

---

client-npm/package.json
client-vue/package.json
client-vue/src/components/PrinterGrid/PrinterTile.vue
client-vue/src/views/HomePrinterGrid.vue
server/package.json
server/yarn.lock

- Fixes #668 
- Fix bg colors printer tiles
- Add default bg color printer filament (striped)

Fix filament border clearer, release new client

---

renovate.json

Enabling lockfile maintenance allows depended packages inside the lockfile to be updated to the latest version.
Please include a summary of the change and which issue is fixed.
Fixes # (issue)
**Test Configuration**:
* Node version:
* OctoPrint version:
* Nodemon/PM2/docker:

Enable Renovate Lockfile maintenance

---

.allcontributorsrc
README.md

Adds the AllContributors rc file and README section

Add All Contributors

---

client-npm/package.json
client-vue/package.json
client-vue/src/backend/printer-firmware-update.service.ts
client-vue/src/backend/server.api.ts
client-vue/src/components/Generic/Actions/PrinterConnectionAction.vue
client-vue/src/components/Generic/Actions/PrinterEmergencyStopAction.vue
client-vue/src/components/Generic/Actions/PrinterSettingsAction.vue
client-vue/src/components/PrinterList/PrinterDetails.vue
client-vue/src/models/plugins/firmware-updates/printer-firmware-state.model.ts
client-vue/src/models/plugins/firmware-updates/prusa-firmware-release.model.ts
client-vue/src/views/Printers.vue
server/controllers/plugin-firmware-update.controller.js
server/package.json
server/services/octoprint/plugin-firmware-update.service.js
server/yarn.lock

673 list firmware versions printerlist

---

client-npm/package.json
client-vue/package.json
client-vue/src/components/PrinterGrid/PrinterTile.vue
server/constants/state.constants.js
server/package.json
server/services/octoprint/constants/octoprint-websocket.constants.js
server/state/printer.state.js
server/yarn.lock

705 offline printer tile style

---

client-npm/package.json
client-vue/package.json
client-vue/src/components/Generic/SideNavs/FileExplorerSideNav.vue
server/package.json
server/yarn.lock

Reword the enable/disable label in sidenav for more clarity

---

client-npm/package.json
client-vue/package.json
client-vue/src/components/Generic/TopBar.vue
server/package.json
server/yarn.lock

Fix calculator and release client

---

docker-compose.yml

fix: docker-compose file

---

client-npm/package.json
client-vue/package.json
server/package.json
server/yarn.lock

release: client 0.3.35

---

client-vue/package.json
client-vue/src/main.ts
client-vue/yarn.lock

feat: push Sentry details

---

server/services/validators/printer-group-service.validation.js

Position printer groups were not allowed to have negative X

fix: position should be from -1 to keep working

---

client-npm/package.json
server/package.json
server/yarn.lock

The client is released with the new dialog fixes for group updates.

Rekease/client 0.3.37

---

client-vue/src/backend/server.api.ts

chore: update client api paths with template string formatting

---

.github/workflows/nodejs.yml
server/package.json

CodeCov not uploading from GHA

fix: codecov path

---

.github/workflows/nodejs.yml
server/jest.config.js

Fix the coverage reporters so CodeCov can work again

fix: cov source

---

server/services/influxdb-v2/influx-db-v2-base.service.js
server/services/task-manager.service.js
server/tasks/boot.task.js
server/tasks/influxdb-query.task.js

Fixes #1070 but found unfixable #1070

fix: skip influx task in case of config failure

---

client-vue/src/components/Generic/NavigationDrawer.vue
client-vue/src/components/Generic/SideNavs/FileExplorerSideNav.vue

This small action got lost in the rush without Vue notifying me about it.

fix: emergency stop with confirmation (sidenav)

---

.github/ISSUE_TEMPLATE/developer_report.md
client-vue/src/utils/array.utils.ts
server/constants/authorization.constants.js
server/constants/server-settings.constants.js
server/container.js
server/container.tokens.js
server/controllers/print-completion.controller.js
server/models/PrintCompletion.js
server/models/Printer.js
server/models/ServerSettings.js
server/services/print-completion.service.js
server/services/validators/print-completion-service.validation.js
server/tasks/print-events.sse.task.js
server/test/application/print-completion-service.test.js
server/utils/array.util.js

feat: completion printer log and grouping API

---

server/server.host.js

fix: switch back to 0.0.0.0 by default

---

server/docker/entrypoint.sh
server/docker/monolithic-entrypoint.sh

Hotfixing the entry files for PM2 in the docker image.

hotfix: docker entrypoints failing

---

server/constants/event.constants.js
server/state/socket-io.gateway.js
server/tasks/printer-socketio.task.js

Helps with increasing the speed of loading the UI

feat: push update over socket immediately after server start

---

client-npm/package.json
client-vue/package.json
client-vue/src/components/PrinterGrid/HomeToolbar.vue
client-vue/src/components/Settings/FdmSettings.vue
client-vue/src/constants/app.constants.ts
client-vue/src/store/printers.store.ts
client-vue/src/utils/uploads-state.utils.ts
server/controllers/validation/printer-files-controller.validation.js
server/package.json
server/tasks/bed-temp-override.task.js
server/yarn.lock

This re-releases the latest changes on dev

re-release hotfix 1.2.1

---

client-vue/src/components/PrinterGrid/HomeToolbar.vue
client-vue/src/constants/app.constants.ts
client-vue/src/directives/file-upload.directive.ts
client-vue/src/store/printers.store.ts

fix: use getters/setters for bedtemp override

---

server/services/floor.service.js
server/tasks/printer-socketio.task.js

**Description**
Client needs some updates/compatibility changes

chore: small fixes client compatibility #1168

---

server/migrations/20220913121347-printergroup-floornumber.js
server/services/floor.service.js

Wrong return statement (too early) in FloorService.

fix: bug returning floor before saving it to database

---

.github/workflows/nodejs_release.yml
server/package.json
server/yarn.lock

fix: install client 1.0.0-rc7

---

server/handlers/logger.js
server/package.json
server/server.constants.js
server/services/multer.service.js
server/utils/fs.utils.js

This is a chore and slight change in file IO, but it is not a breaking change.

fix: put all stored data in one folder

---

server/package.json
server/services/printer.service.js

- Remove outlet current (InfluxDB2) plugin and task
- Remove bedtemp override
- Add client dist download with github octokit
- Remove group construct, flatten to pure floor based printer positioning system

release: 1.3.0

---

server/package.json
server/yarn.lock

Chore to update fallback client

chore: install latest client with server's release 1.3.0

---

docs/guides/monsterpi.md
docs/guides/setup.md
docs/index.md

Add MonsterPi to docs for having a permalink

fix: MonsterPi added to docs

---

installations/.gitignore
installations/other/README.md
installations/other/home-assistant/docker-compose.yml
installations/other/mosquitto-broker/docker-compose.yml
installations/other/octoprint-virtual/docker-compose.yml
server/package.json
server/server.constants.js
server/server.env.js
server/yarn.lock

Add configuration and docker compose resources for testing/experimenting with mqtt autodiscovery.
The .gitignore file added is the most important part: allows for easier branch switching.

feat: add configuration for a future mqtt autodiscovery plugin

---

server/package.json
server/services/client-bundle.service.js

Fixes the client bundle download check

fix: dist/ missing in bundle version check

---

docs/guides/monsterpi.md
installations/fdm-monster-node-linux/update-fdm-monster.sh

Adds some nice docs about MonsterPi 0.2.0 and manually updating FDM Monster inside.

docs: update MonsterPi manual update

---

docs/guides/monsterpi.md

Documentation fixes for MonsterPi.

docs: reformat MonsterPi docs [skip ci]

---

.github/_config.yml
docs/_config.yml
docs/guides/monsterpi.md

fix: docs styling and copyright

---

docs/guides/windows_service.md
server/container.js
server/container.tokens.js
server/controllers/server-public.controller.js
server/package.json
server/services/monsterpi.service.js
server/test/application/monsterpi-service.test.js

Very small file readout to check the distribution

feat: add service to detect MonsterPi distribution version

---

server/container.js
server/container.tokens.js
server/controllers/printer-files.controller.js
server/controllers/server-public.controller.js
server/controllers/validation/printer-files-controller.validation.js
server/package.json
server/services/batch-call.service.js

Batch call service #1748 has been implemented, but by adding a feature flags API we can safely introduce this into the client without creating too many problems. Added versioning to feature flags for compatibility across versions.
Due to this strategy the API is a patch release.

1748 batch call service & feature flags api

---

server/controllers/validation/printer-files-controller.validation.js
server/test/api/printer-files-controller.test.js
server/test/application/batch-call-service.test.js

fix: validation rules incorrect w.r.t. mongoId, test: cover API

---

docs/guides/docker_compose.md

Removed emojis from the page and used words to express the same meaning
Rewrote the headings to be more descriptive
Replaced the exclamation marks with periods to make the sentences more professional
Removed contractions to make the text more formal
Rewrote some of the sentences to make them clearer and more concise
Added punctuation where necessary
Used bullet points to organize some of the information
Removed unnecessary abbreviations
Removed an unnecessary sentence that contained no information
Rewrote some of the sentences to avoid using colloquial expressions
Removed unnecessary words and phrases
Made the language more professional and understandable
Fixes #1637 

Update docker_compose.md [skip ci]

---

docs/guides/env_config.md
docs/guides/linux_service.md
docs/guides/monsterpi.md
docs/guides/updating_client_bundle.md
docs/guides/windows_service.md

Updated docs [skip ci]

---

docs/guides/updating_client_bundle.md

The client bundle page has been improved based on work by @Dumnersm580 https://github.com/fdm-monster/fdm-monster/pull/1760

docs: apply the changes to client bundle

---

docs/guides/windows_service.md
installations/fdm-monster-node-windows/download-fdm-monster-server.ps1

The windows documentation is highly confusing. The service installation is much simpler and the docs should reflect this.

docs: make windows setup documentation much less bloated

---

docs/_layouts/default.html

Fixed favicon bug by adding a custom layout
Fixes #1727 

fixed favicon

---

docs/guides/linux_service.md
docs/index.md

docs: fix wrong link pointing Linux to Windows docs instead

---

server/package.json

Testing the docker release mechanism

chore: test stub release 1.4.0-rc1

---

server/controllers/settings.controller.js
server/test/api/settings-controller.test.js

This reverts an unfortunate choice made in release 1.3.7

revert: 1.3.7 release api route change

---

docs/configuration/configuration.md
docs/configuration/preconfiguration.md
docs/configuration/settings.md
docs/configuration/settings/grid_settings.md
docs/configuration/updating_client_bundle.md
docs/configuration/yaml_import_export.md
docs/guides/docker_compose.md
docs/guides/windows_service.md
docs/index.md

Apparently it's YYYY-MM-DD not YYYY-DD-MM (@Dumnersm580 please be aware, I believe this is European format)

docs: hotfix the invalid date formats

---

docs/configuration/settings/grid_settings.md
docs/configuration/settings/settings.md

A second tier child needs a grand_parent.
https://docs.simpleinvoices.org/docs/navigation-structure/#children-with-children

hotfix: added grand_parent to child of child [skip ci]

---

server/services/octoprint/octoprint-rxjs-websocket.adapter.js
server/state/printer.state.js

Detect stale sockets by exposing the last received message timestamp

feat: add last message date to detect silent sockets

---

server/handlers/logger.js
server/server.constants.js

fix: combine logs into 1 file

---

.github/workflows/nodejs.yml
.github/workflows/nodejs_release.yml

feat: test release logic for release workflow inside PR workflow

---

server/state/printer-socket.store.js

Fixes the undefined length in the log

fix: log should determine length of keyvalue object not as array

---

server/controllers/printer.controller.js
server/state/printer-socket.store.js

Reset the socket state after a printer create/update. This ensures that at least an attempt is done to establish a connection.

fix: socket is retried on printer update

---

installations/fdm-monster-node-linux/install-fdm-monster.js

fix: change rootpath

---

docs/guides/monsterpi.md

The latest RC of MonsterPi was added.

docs: add monsterpi release 0.2.2-rc2

---

server/state/test-printer-socket.store.js

Small bugfix to avoid cluttering the frontend test checks panel

fix: filter unrelated events for tests

---

server/server.constants.js
server/services/octoprint/octoprint-sockio.adapter.js

I noticed from an experimentation version that there were some diffs that might be nice to add.
They should be verified thoroughly though before being merged.

chore: tackle some state changes (up for experimentation)

---

server/controllers/server-public.controller.js
server/controllers/settings.controller.js
server/controllers/validation/setting.validation.js
server/services/settings.service.js
server/state/settings.store.js

This feature is crucial, adds a feature flag.

feat: expose anonymousDiagnosticsEnabled setting as endpoint

---

server/controllers/printer.controller.js
server/controllers/server-public.controller.js
server/services/octoprint/octoprint-api.routes.js
server/tasks/socketio.task.js

feat: add pause resume job commands api endpoints

---

docs/guides/windows_service.md

docs: typo in uninstalling the service

---

docs/guides/docker_compose.md
docs/guides/installations.md

Nonexisting tags were described, removed those.

docs: fix tags

---

docker-compose.yml
docs/guides/docker_compose.md

As mentioned by @tophattwaffle in DM.

docs: adjust docker media folder

---

server/state/printer-socket.store.js

This batches up any reauth and reopen attempt in Promise.all sense. This will hammer the CPU, but at least leave room for some NodeJS event loop to breathe a bit after boot.

feat: batch reauth and setup calls in Websocket task to speed up timeout delays

---

server/state/printer-socket.store.js

This improves the batched promises from influencing each other.

fix: catch errors in tasks with websocket setup promise failure

---

docs/_config.yml
docs/index.md

docs(fix): main page styling

---

README.md
server/services/floor.service.js
server/test/api/floor-controller.test.js
server/test/api/test-data/create-printer-floor.js

chore: fix printer floor typos

---

server/controllers/printer.controller.js
server/controllers/validation/printer-controller.validation.js
server/services/multer.service.js
server/services/octoprint/octoprint-api.routes.js
server/services/octoprint/octoprint-api.service.js
server/services/octoprint/utils/api.utils.js
server/state/printer.cache.js
server/test/api/auth-controller.test.js
server/test/api/printer-controller.test.js
server/test/mocks/octoprint-api.mock.js

Feature/2123 create or restore backup octoprint batch UI following after

---

server/controllers/auth.controller.js
server/controllers/printer-settings.controller.js
server/server.host.js

This is a public API that can be called to inquire whether login is required or not. This allows the client to call this peacefully without getting a 401 error.

feat: add public endpoint indicating auth is required

---

server/controllers/user.controller.js
server/middleware/authenticate.js

Send empty profile when no user.id is given

fix: dont load profile on unauthenticated mode

---

server/package.json
server/server.constants.js
server/yarn.lock

feat: install latest client

---

server/.env.template
server/middleware/passport.js

Fixes a configuration problem.

fix: load issuer and audience from config instead of defaults

---

server/controllers/printer.controller.js
server/exceptions/runtime.exceptions.js
server/middleware/authenticate.js
server/middleware/exception.handler.js

Test and reformat Authorization errors with actual problem.

fix: reformat returned authz body

---

server/services/authentication/user.service.js

fix: comparePasswordHash

---

.swcrc
jest.config.js
package.json
server/server.host.ts

Source maps will help tools like Sentry.

fix: enable sourcemaps and fix awilix controller loading wrongly

---

src/server.env.ts
src/utils/env.utils.ts

fix: remove writing to env file

---

src/controllers/settings.controller.ts
src/services/camera-stream.service.ts
src/services/interfaces/camera-stream.dto.ts
src/services/interfaces/camera-stream.service.interface.ts
src/services/interfaces/printer.dto.ts
src/services/settings.service.ts
src/services/validators/settings-service.validation.ts
src/shared.constants.ts
src/state/settings.store.ts
src/tasks/boot.task.ts

- Fix rules
- Define camera stream interface

fix: settings controller validation change wrt service, chore: cleanup interface of camera stream definition api

---

src/constants/server-settings.constants.ts
src/controllers/camera-stream.controller.ts
src/controllers/server-public.controller.ts
src/models/index.ts
src/services/batch-call.service.ts
src/services/interfaces/gcode-analysis.dto.ts
src/services/interfaces/printer-file.dto.ts
src/services/interfaces/printer-files.service.interface.ts
src/services/interfaces/settings.dto.ts
src/services/printer-files.service.ts

Required to do proper connectivity checks at client load time

feat: public test api endpoint for connectivity checks

---

src/controllers/auth.controller.ts

Expose registration without auth

fix: expose registration enabled flag without auth

---

src/exceptions/runtime.exceptions.ts
src/middleware/authenticate.ts
src/middleware/exception.handler.ts
src/models/Auth/Role.ts
src/models/Auth/User.ts
src/models/PrintCompletion.ts
src/models/Printer.ts
src/services/authentication/auth.service.ts
src/services/authentication/user.service.ts
src/services/interfaces/user-service.interface.ts
src/services/interfaces/user.dto.ts
src/services/printer.service.ts

Password change required would cause issues after login was issued. Now it is thrown as 409 as well as a reject before login with 409.

fix: handle password changed required before login and with 409 CONFLICT

---

src/controllers/plugin-firmware-update.controller.ts
src/controllers/printer-settings.controller.ts
src/handlers/validators.ts
src/services/octoprint/octoprint-api.routes.ts
src/services/octoprint/octoprint-api.service.ts
src/services/octoprint/plugin-base.service.ts
src/services/octoprint/plugin-firmware-update.service.ts
src/services/print-completion.service.ts

fix: typing octoprint service

---

src/models/CameraStream.ts
src/services/floor.service.ts
src/services/printer.service.ts
src/services/settings.service.ts
test/api/test-data/create-printer.ts
test/api/test-data/create-user.ts
test/api/user-controller.test.ts
test/application/printer-files-service.test.ts

fix: remove _id usage as much as possible

---

package.json
src/server.constants.ts
yarn.lock

Release 1.5.0-rc1 with minimum client 1.3.7

release: 1.5.0-rc1

---

src/services/authentication/auth.service.ts

Small forgotten return statement

fix: nullref bug authService userRefreshToken.expiredAt

---

src/services/validators/settings-service.validation.ts

For testing auth and refresh flows.

feat: in dev mode we should be able to have lower jwt expiry

---

docker-compose.yml
src/middleware/global.middleware.ts

Crucial fix for any setup that only has the UI to work with (like MonsterPi).

Hotfix/2447 api blocks UI on first time setup allow UI to be loaded on first time setup

---

package.json
src/controllers/user.controller.ts
src/server.constants.ts
src/services/authentication/role.service.ts
src/services/interfaces/role-service.interface.ts
test/api/user-controller.test.ts
test/application/role-service.test.ts
yarn.lock

fix: role management

---

installations/fdm-monster-node-linux/update-fdm-monster.sh

fix: update script should be changed to new dist download method

---

src/constants/authorization.constants.ts
src/controllers/print-completion.controller.ts
src/services/core/yaml.service.ts
src/services/floor.service.ts
src/services/interfaces/floor.dto.ts
src/services/interfaces/floor.service.interface.ts
src/services/validators/floor-service.validation.ts
src/services/validators/yaml-service.validation.ts
test/api/camera-stream.controller.test.ts
test/api/custom-gcode-controller.test.ts
test/api/print-completion-controller.test.ts
test/api/printer-controller.test.ts
test/api/printer-settings-controller.test.ts
test/api/server-private-controller.test.ts
test/api/settings-controller.test.ts
test/api/tasks/websocket-task.test.ts
test/api/test-data/create-floor.ts
test/api/test-data/create-printer.ts
test/api/user-controller.test.ts
test/application/batch-call-service.test.ts
test/application/store/file-cache.test.ts
test/application/store/printer-store.test.ts
test/application/task-manager.service.test.ts
test/application/test-data/yaml-import.ts
test/application/yaml-service.test.ts
test/setup-global.ts
test/typeorm.manager.ts

- Test fixes/chores
- Study SQLite migration process and reduce impact

fix: slowly introduce isTypeormMode flag and backward compatibility YAML export/import

---

src/constants/service.constants.ts
src/services/interfaces/floor.service.interface.ts
src/services/octoprint/octoprint-api.service.ts
src/services/validators/floor-service.validation.ts
src/state/floor.store.ts

Some changes that have no impact, split off from #2445

chore: small non breaking TS changes

---

src/services/core/task-manager.service.ts
test/api/host/boot-task.test.ts

Old code, needed a brush over.

chore: upgrade boot task

---

package.json
src/consoles/upload-test.ts
src/constants/service.constants.ts
src/controllers/printer-files.controller.ts
src/models/Printer.ts
src/mongo-migrations/20231202183902-printer-files-simpler.ts
src/services/core/multer.service.ts
src/services/interfaces/printer-files.service.interface.ts
src/services/octoprint/octoprint-api.routes.ts
src/services/octoprint/octoprint-api.service.ts
src/services/octoprint/utils/api.utils.ts
src/services/printer-files.service.ts
src/state/file-upload-tracker.cache.ts
src/state/file.cache.ts
src/state/printer-files.store.ts
src/state/printer.cache.ts
src/state/settings.store.ts
src/types/express/index.d.ts
src/utils/find-predicate.utils.ts
test/api/printer-files-controller.test.ts
test/application/printer-files-service.test.ts
test/application/store/file-cache.test.ts
test/application/store/files-store.test.ts
yarn.lock

- Drop `got`
- Implement upload tracking with pure `axios` implementation
- Write test server + receiver in multipart and pure-binary form
- Fixes multipart by calculating content length
- Clean up OctoPrint API service

Fix/2637 drop got, octoprint file upload do-over

---

.github/workflows/docker_quick_build.yml
.github/workflows/docker_release.yml
docker-compose.yml
docs/installations/docker_compose.md

Dockerhub change `davidzwa/fdm-monster` to `fdmmonster/fdm-monster`

fix: add new reference to dockerhub

---

README.md

Please include a summary of the change and which issue is fixed.
Fixes # (issue)
**Test Configuration**:
* Node version:
* OctoPrint version:
* Nodemon/PM2/docker:

Update README.md image

---

src/controllers/batch-call.controller.ts
src/services/batch-call.service.ts
src/services/octoprint/octoprint-api.service.ts

Batch response times API with batch service

feat: batch response time measurement

---

.github/workflows/nodejs.yml

fix: use CODECOV_TOKEN

---

src/state/file-upload-tracker.cache.ts

fix: uploads cache was not tracking upload completion properly

---

src/services/batch-call.service.ts
src/state/printer-socket.store.ts

Fix disabled / missing sockets should not prevent others from reconnecting (emergency action).

fix: disabled printers should not intervene with a disconnected socket

---

package.json
src/controllers/printer.controller.ts
src/controllers/server-public.controller.ts
src/services/octoprint/dto/websocket-output/current-message.dto.ts
src/services/octoprint/octoprint-api.routes.ts
src/services/octoprint/octoprint-api.service.ts
src/services/octoprint/plugin-repository.cache.ts
yarn.lock

Send API commands to jog and home the axes.

feat: move and home axes

---

src/services/core/yaml.service.ts
src/services/interfaces/floor.service.interface.ts
src/services/interfaces/printer.service.interface.ts
src/services/validators/yaml-service.validation.ts
test/application/test-data/export-fdm-monster-1.5.2-mongodb.yaml
test/application/test-data/export-fdm-monster-1.6.0-sqlite.yaml
test/application/test-data/yaml-import.ts
test/application/yaml-service.test.ts
test/test-server.ts

Fixes the problem with YAML import, reported by @windarrow3d 🥳

test: test since when floor position import started to fail

---

src/data-source.ts
src/entities/print-completion.entity.ts
src/migrations/1708465930665-ChangePrintCompletionDeletePrinterCascade.ts

fix: deleting a printer now deletes its completions as well

---

src/container.ts
src/controllers/settings.controller.ts

fix: inject server version

---

RELEASE_NOTES.MD
src/controllers/settings.controller.ts
src/services/orm/settings.service.ts

Adds validation on API level. This means the settings API will become a **lot more strict**. This is good, if properly tested.

fix: file clean settings should be validated before update

---

src/services/orm/printer-files.service.ts
src/services/print-completion.service.ts

Reported through a github issue. Diagnostics came from Sentry.

fix:  SQLite two common query problems: PrintCompletionContext and new file hash undefined for folders

---

src/services/core/yaml.service.ts
src/shared/websocket.adapter.ts
src/state/file-upload-tracker.cache.ts

chore: changes without specific context

---

src/controllers/printer.controller.ts
src/middleware/printer.ts

Resolve OctoPrint for all printer types as Moonraker is not supported yet.

Resolve OctoPrint instead of error, since Moonraker is not supported yet

---

src/constants/server-settings.constants.ts
src/controllers/settings.controller.ts
src/entities/settings.entity.ts
src/models/Settings.ts
src/services/interfaces/settings.dto.ts
src/services/orm/settings.service.ts
src/services/validators/settings-service.validation.ts
src/state/settings.store.ts
test/api/settings-controller.test.ts

Adds setting needed for toggling Moonraker support on or off.

feat: add experimental moonraker support setting to model, validation and API endpoints

---

RELEASE_NOTES.MD
jest.config.js
tsconfig.json

fix: swc sourcemap inline to hit breakpoints during test, chore: update to es2022

---

RELEASE_NOTES.MD
src/constants/server-settings.constants.ts
src/entities/settings.entity.ts
src/models/Settings.ts
src/services/interfaces/settings.dto.ts
src/services/mongoose/settings.service.ts
src/services/orm/settings.service.ts
src/state/settings.store.ts
test/api/settings-controller.test.ts

Fix that should not cause any problems.

fix: printer file clean could contain extra data, skim those props off

---

RELEASE_NOTES.MD
src/constants/server-settings.constants.ts
src/services/interfaces/settings.dto.ts
src/state/settings.store.ts
test/api/settings-controller.test.ts

feat: expose typeorm setting and adjust test

---

.github/workflows/nodejs.yml
.github/workflows/nodejs_mongodb.yml
.github/workflows/nodejs_release.yml
RELEASE_NOTES.MD

Upgrade workflow to node 20 (this is not a requirement yet)

feat: upgrade workflows to node 20

---

package.json
src/constants/server-settings.constants.ts
src/controllers/settings.controller.ts
src/entities/settings.entity.ts
src/models/Settings.ts
src/server.constants.ts
src/server.host.ts
src/services/interfaces/settings.dto.ts
src/services/mongoose/settings.service.ts
src/services/orm/settings.service.ts
src/services/validators/settings-service.validation.ts
src/state/settings.store.ts
test/api/settings-controller.test.ts
yarn.lock

feat: ability to switch client to @fdm-monster/client-next line

---

RELEASE_NOTES.MD
requests/moonraker/api_printer.http
requests/moonraker/printer_objects_webhooks.http
src/services/core/batch-call.service.ts
src/services/interfaces/printer-file.dto.ts
src/services/moonraker.api.ts
src/services/moonraker/dto/server-history/history-list.dto.ts
src/services/moonraker/moonraker.client.ts
src/services/octoprint.api.ts
src/services/octoprint/octoprint.client.ts
src/services/octoprint/utils/file.utils.ts
src/services/printer-api.interface.ts

feat: implement batch service (reprint, connect, settings) for new Printer API (not OctoPrint specific)

---

docker/Dockerfile
docker/alpha.Dockerfile
docker/test.Dockerfile

Inside dockerfile files, the annotation for docker commands need to be the same.
~~- [ ] New feature (non-breaking change which adds functionality)~~
~~- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)~~
~~- [ ] This change requires a documentation update~~
~~- [ ] Vue test~~
~~- [ ] Node test~~
~~- [ ] I have covered my changes with tests~~

(build) fix docker file annotation

---

RELEASE_NOTES.MD
src/services/orm/base.service.ts
test/application/user-service.test.ts

fix: catch null or undefined id before querying database

---

.env.template
RELEASE_NOTES.MD
package.json
src/constants/server-settings.constants.ts
src/controllers/settings.controller.ts
src/entities/settings.entity.ts
src/middleware/global.middleware.ts
src/models/Settings.ts
src/server.constants.ts
src/server.core.ts
src/services/interfaces/settings.dto.ts
src/services/interfaces/settings.service.interface.ts
src/services/mongoose/settings.service.ts
src/services/orm/settings.service.ts
src/services/validators/settings-service.validation.ts
src/state/settings.store.ts
test/api/settings-controller.test.ts
test/application/settings.service.test.ts
test/setup-global.ts
yarn.lock

feat: remove experimental 🧪 whitelist settings and ip package (CVE)

---

src/controllers/auth.controller.ts

fix: demo mode should never show first-time-setup

---

RELEASE_NOTES.MD
src/controllers/camera-stream.controller.ts
src/controllers/plugin-firmware-update.controller.ts

Fix/camera controller not guest protected (not readonly)

---

RELEASE_NOTES.MD
src/constants/server-settings.constants.ts
src/entities/settings.entity.ts
src/models/Settings.ts
src/services/interfaces/settings.dto.ts
src/services/mongoose/settings.service.ts
src/services/validators/settings-service.validation.ts
test/api/settings-controller.test.ts

feat: add grid setting for UI to show cancel button instead of quick stop button

---

src/controllers/printer-files.controller.ts
src/services/octoprint.api.ts
src/services/octoprint/octoprint.client.ts
src/utils/normalize-url.ts
test/api/printer-files-controller.test.ts
test/domain-shared/ url-encoding.test.ts

fix: update normalize-url sindresorhus and fix file url encoding

---

README.md

Updated the README.md screenshot to v1.8.0 of FDM Monster

Update README.md - updated screenshot

---

RELEASE_NOTES.MD
src/controllers/server-private.controller.ts
src/services/core/yaml.service.ts
src/services/validators/yaml-service.validation.ts

fix: yaml import regressions

---

docker-compose.yml

Update docker-compose.yml with sqlite instructions

---

RELEASE_NOTES.MD
package.json
src/container.ts
test/api/auth-controller.test.ts
test/api/batch-call-controller.test.ts
test/api/camera-stream.controller.test.ts
test/api/floor-controller.test.ts
test/api/printer-controller.test.ts
test/api/printer-group.controller.test.ts
test/api/server-private-controller.test.ts
test/application/print-completion-service.test.ts
test/application/test-data/printer.data.ts
test/test-server.ts
yarn.lock

chore: fix punycode userland alternative warning

---

RELEASE_NOTES.MD
src/container.tokens.ts
src/controllers/auth.controller.ts
src/controllers/batch-call.controller.ts
src/controllers/camera-stream.controller.ts
src/controllers/custom-gcode.controller.ts
src/controllers/first-time-setup.controller.ts
src/controllers/floor.controller.ts
src/controllers/print-completion.controller.ts
src/controllers/printer-files.controller.ts
src/controllers/printer-group.controller.ts
src/controllers/printer-settings.controller.ts
src/controllers/printer.controller.ts
src/controllers/server-private.controller.ts
src/controllers/server-public.controller.ts
src/controllers/settings.controller.ts
src/controllers/user.controller.ts
src/controllers/validation/printer-settings-controller.validation.ts
src/handlers/printer-resolver.ts
src/handlers/validators.ts
src/middleware/authenticate.ts
src/middleware/demo.middleware.ts
src/middleware/exception.filter.ts
src/middleware/global.middleware.ts
src/middleware/param-converter.middleware.ts
src/server.host.ts
src/shared/load-controllers.ts
src/types/express/index.d.ts
test/api/first-time-setup.controller.test.ts

feat: all API controllers have been updated to decorator based routing

---

src/consoles/http-file-receiver.console.ts
src/consoles/launch-http-servers.ts
src/consoles/utils/api-messages.ts
src/consoles/utils/delayed-memory.storage.ts
src/consoles/utils/ws-messages.ts
src/services/moonraker/moonraker-websocket.adapter.ts
src/services/octoprint/octoprint-websocket.adapter.ts
src/shared/websocket.adapter.ts

It's been challenging to test at scale. With a new OctoPrint mock server and a console which can replicate to scale up to many mock instances, we can test in a more standardized manner.

Feat introduce octoprint mock server + scale-up console

---

.env.template
RELEASE_NOTES.MD
src/handlers/logger.ts
src/server.constants.ts

fix: make colored logs opt-in with "ENABLE_COLORED_LOGS: true" env var

---

RELEASE_NOTES.MD
package.json
src/constants/server-settings.constants.ts
src/entities/settings.entity.ts
src/models/Settings.ts
src/server.constants.ts
src/services/moonraker/moonraker-websocket.adapter.ts
src/services/moonraker/moonraker.client.ts
src/services/octoprint/octoprint.client.ts
src/services/prusa-link/prusa-link.api.ts
src/services/validators/settings-service.validation.ts
src/shared/runtime-settings.migration.ts
test/api/settings-controller.test.ts
yarn.lock

feat: introduce separate upload timeout setting for better control and resilience

---

RELEASE_NOTES.MD
src/handlers/logger-factory.ts
src/handlers/logger.ts
src/handlers/logging/file-logging.transport.ts
src/handlers/logging/loki-logging.transport.ts
src/handlers/logging/static.logger.ts
src/index.ts
src/server.env.ts
src/services/core/github.service.ts
test/api/host/server-env.test.ts
test/application/store/files-store.test.ts
test/setup-after-env.ts
test/test-server.ts

Fixes #4307. Optimizes logger setup, makes logger setup code cleaner and more maintainable
Local test and unit test
**Test Configuration**:

fix: logger is now static, reducing memory usage and test duration

---

RELEASE_NOTES.MD
package.json
src/controllers/printer-files.controller.ts
src/controllers/validation/printer-files-controller.validation.ts
src/server.constants.ts
src/services/moonraker.api.ts
src/services/moonraker/moonraker.client.ts
src/services/octoprint.api.ts
src/services/octoprint/octoprint.client.ts
src/services/printer-api.interface.ts
src/services/prusa-link/prusa-link.api.ts
test/api/printer-files-controller.test.ts
test/requests/printer-file/upload-file.http
yarn.lock

4090 [Feature]: Add option to upload GCode files but not start printing
