.github/workflows/docker_quick_build.yml
.github/workflows/docker_release.yml
server/test/api/printer-controller.test.js
server/test/application/cache/jobs-cache.test.js

Fixes an API test for deleting a printer - should work just fine. It's my thought it is due to the test cleaning up too fast. Might explain why it fails only a part of all runs

Look if the printer api DELETE call fails because of the test cleanup

---

client-vue/src/views/HomePrinterGrid.vue

Adds the selection count for clearing the amount of selected printers more easily.

Vue2 - show selected printers count (printer grid)

---

renovate.json

Bugfix renovate should ignore Node12 Dockerfile and Vue2 should only be minor updates

---

renovate.json

Further followup fixes of specific issue
"Bugfix renovate should ignore Node12 Dockerfile and Vue2 should only be minor updates"

Renovate ignore Docker major and specific Vue2 fixed majors

---

client-vue/src/components/Generic/SideNavs/FileExplorerSideNav.vue

This was a bug found in the process of Vue2=>Vue3 migration
https://github.com/fdm-monster/fdm-monster-client/issues/85

Shift tooltips to left instead of bottom for clearer view

---

client-vue/src/views/Printers.vue

Small follow-up fix for printers search
This one does not adjust the count when filtering. Technically this is a bit more complex and luckily the paginator shows it at the bottom.

Also adjust printer list with filter count

---

server/package.json
server/yarn.lock

Force `got` to be resolved to 11.8.5 as it is used by the developed package `nodemon` (or a notifier package pointing to ... pointing to ...). I do not care about a request for package updates from NPM.

Remove older got version

---

client-npm/package.json
client-vue/package.json
client-vue/src/components/PrinterGrid/PrinterTile.vue
client-vue/src/models/printers/printer.model.ts
server/state/printer.state.js

- Fixes the RAL processing applied to represent printer tile border color 
- Only process recognized RAL colors (backend)

Apply RAL code scanning in client 0.3.17

---

server/package.json
server/server.env.js
server/tasks/boot.task.js
server/yarn.lock

Date-FNS slows down the docker production build. `migrate-mongo` has been removed from our runtime.

fix: halted/slowdown docker build due to date-fns

---

client-vue/src/store/printers.state.ts
client-vue/src/views/Printers.vue

The list now shows the printer group, sadly it is not sortable.

fix: show printer group in list

---

client-vue/src/components/PrintTimeline/PrintCompletionTimeline.vue

feat: add printer name filter

---

client-vue/src/components/PrinterGrid/HomeToolbar.vue

The toggle was sometimes unset when clicked, which was causing illegal visual state.

fix: make floor toggle always selected

---

server/services/octoprint/octoprint-api.service.js

In production the uploaded files were not purged from file system after upload. This caused high volume size and docker VIRT memory problems.

hotfix: delete files after upload

---

server/services/octoprint/constants/octoprint-websocket.constants.js
server/services/octoprint/octoprint-rxjs-websocket.adapter.js

The websocket state often becomes silent. This causes the server to not act and keep outdated state.
Need a silence tracker and reauth.

fix: add last update time in printer state

---

server/package.json
server/yarn.lock

This installs the client which doesnt use `/printer-group` anymore. Instead it uses floors to position printers.

feat: install client 1.0.0-rc6

---

server/migrations/20230427202911-printer-remove-sortindex.js
server/models/Printer.js
server/package.json
server/services/printer.service.js
server/state/printer.state.js
server/test/api/printer-controller.test.js
server/test/application/store/printer-store.test.js
server/test/domain/printer-schema.test.js

Remove the SortIndex property from printers as it's not a suitable fit for how printers are sorted in @fdm-monster/client

chore: remove SortIndex with migration

---

server/constants/state.constants.js

The color previously used is the same as Printing, causing confusion.

fix: differentiate paused pausing colors

---

docs/index.md

docs: fix the wrong link to /docs/guides [skip ci]

---

docs/guides/monsterpi.md

The URL works if I dont add :80 for HTTPS access.

docs: fix the URL for https self-signed access [skip ci]

---

.github/workflows/nodejs_release.yml

Adds a build number to new release numbers hitting develop (f.e. 1.2.3-1234) to avoid develop taking the release.
Creates a draft release that I can decide to rename, retag or remove.

fix: ensure develop releases are done using buildnr

---

server/services/yaml.service.js

The YAML export was not correctly using the printer name property to export, resulting in an empty settingsAppearance.

fix: yaml export should use the right printer name property

---

server/services/client-bundle.service.js

The client bundle extraction path was inside the server folder, which is wrong.

fix: client bundle was extracted to the wrong folder

---

installations/fdm-monster-node-linux/update-fdm-monster.sh
installations/fdm-monster-node-windows/download-update.ps1
server/package.json
server/services/github.service.js
server/tasks/client-bundle.task.js

Without a GITHUB_PAT the updater failed. Now it will not pursue an authenticated connection flow per default.

fix: update scripts and avoid auth when no GITHUB_PAT

---

.gitignore
installations/other/octoprint-virtual/default1.9.0/octoprint.Dockerfile
installations/other/octoprint-virtual/default1.9.0/run
installations/other/octoprint-virtual/docker-compose.simple.yml
installations/other/octoprint-virtual/docker-compose.yml

A swarm stack has been added which can replicate a bunch of (virtual) OctoPrints.
OctoPrint can be preconfigured by adding the `config.yaml` and `users.yaml` files of your liking.
The files will be preseeded right before and everytime the OctoPrint service is started.

feat: add docker swarm stack

---

server/services/octoprint/octoprint-sockio.adapter.js

fix: global API key detector filter was not correct when doing apikey check

---

server/controllers/settings.controller.js
server/controllers/validation/setting.validation.js
server/models/ServerSettings.js
server/services/settings.service.js
server/state/settings.store.js

Sentry is now disabled by default and the word 'anonymous' has been removed to ensure transparency to the user.

fix: set Sentry diagnostics to disabled by default (opt-in)

---

docs/software_usage/creating_printers.md
docs/software_usage/organizing_floors.md

Small TOC reference section issue due to a `#` typo

docs: fix bug in child page TOC reference sections software usage

---

docker-compose.yml
docs/guides/docker_compose.md
server/tasks/boot.task.js

There might have been database start hiccups (as often happens when MongoDB starts).
What I find fascinating is that the disabled BootTask job was rescheduled perfectly, but for some reason the SAFEMODE_ENABLED mode was triggered. This is only possible if the `bootTaskScheduler` was not provided (leaving it to false by default and thus skipping boot tasks).
Could it be that the scheduled disabled task does not perform runOnce? Yep I just confirmed this!

fix: add error log for failing database connections at boot

---

server/container.js
server/container.tokens.js
server/controllers/server-private.controller.js
server/package.json
server/server.constants.js
server/services/log-dump.service.js

Adds the ZIP endpoint at:
`prefix://HOSTNAME/api/server/dump-fdm-monster-logs`
For example:
`http://monsterpi.local:4000/api/server/dump-fdm-monster-logs`

feat: add get,post log dump in ZIP format with adm-zip

---

server/tasks/boot.task.js
server/tasks/print-completion.socketio.task.js
server/tasks/printer-websocket.task.js
server/tasks/socketio.task.js

As of 1.4.x we're sticking with JSDoc quite a bit. This is a chore to step more towards removing the private property in NodeJS with `#`.

chore: rename private properties to public for ease of migration

---

installations/fdm-monster-node-linux/uninstall-fdm-monster.js
installations/fdm-monster-node-linux/update-fdm-monster.sh

These are not perfect changes, as the scripts depend on the repo being downloaded... this is not a good approach in the long run.
The linux service bootstrapping should be redone from the ground up similar to how the windows service install is done.

fix: path issues uninstall js script and update bash script

---

docs/_config.yml

Referring Fluidd's JTD setup, this change was missing.

[ci skip] docs(fix): set color scheme to match scss file name

---

docs/_config.yml
docs/_sass/color_schemes/docs.scss
docs/index.md

- Adjust the main page text
- Brighten the main theme color
- Add the 'back to top' link

docs(fix): adjust index text, brighten layout color, add back to top [ci skip]

---

server/constants/server-settings.constants.js
server/models/ServerSettings.js
server/services/multer.service.js
server/services/settings.service.js

Now that the project is gaining more traction from users and developers, it is important to avoid confusion in the code.
This chore involves removing properties from the ServerSettings model/schema which are not used internally, undocumented nor exposed to the UI in any way. They were future ideas, but for now its best to remove them.

fix: remove unused ServerSettings properties to avoid confusion, clean up multer service

---

server/constants/server-settings.constants.js
server/utils/correlation-token.util.js

This sets the random key to a uuid v4 which is like this:
`eec2b7cb-3e39-4034-b83e-c2ddbbe5e8cd`
So it meets the requirements of minimum 5 characters instead of 10.

fix: random key should be of minimum length

---

docker-compose.yml
docs/installations/docker_compose.md
installations/ansible/playbook.yaml

- Adds an ansible script to run mongodb through change of authentication
- Adjusts default docker-compose to be more resilient for new users wanting to change credentials (INITDB issue w.r.t. authSource configuration)  and simplifies mongo volume mapping
- adjusts docs with docker-compose template

chore: add ansible script to test mongodb (requires linux, python3, pip3, ansible and pymongo)

---

server/package.json
server/yarn.lock

MikroORM is not used yet and an small bump on the road prevents it from being included in the next release. 
Therefore the dependencies are removed.

revert: remove MikroORM dependencies

---

.github/workflows/nodejs.yml

In order to ensure that release workflows work, we can dryrun the actions as well as possible.

dry-run the publish action

---

.github/workflows/docker_quick_build.yml

1) The github run build number was leaving behind too many tags on the docker.io CR. Instead I've decided for a develop suffix.
2) The GHA workflow will run at night.

fix: nightly develop docker build, drop run build number

---

src/container.tokens.ts
src/container.ts
src/controllers/printer-files.controller.ts
src/services/batch-call.service.ts
src/state/printer-files.store.ts
src/tasks/boot.task.ts
src/tasks/printer-file-clean.task.ts
test/application/store/files-store.test.ts
test/application/store/printer-store.test.ts
test/application/store/settings-store.test.ts

The files store implement does not scale well:
- files are often stale or non-consistent with the remote service (aka OctoPrint)
- the JSON structure is embedded in printers on MongoDB level which is not fully compatible with a future relational database 
- batch reprint often triggers old files
- the stored files are in OctoPrint dir/storage structure, does this scale with a distributed file storage like minio/azurite?
- keep the file list unnested, remove storage free/folders etc

fix: improve files store consistency

---

.env.template
docker/test.Dockerfile
jest.config.js
package.json
src/constants/service.constants.ts
src/controllers/print-completion.controller.ts
src/controllers/printer-files.controller.ts
src/entities/base.entity.ts
src/models/Printer.ts
src/models/PrinterFile.ts
src/models/index.ts
src/services/interfaces/print-completion.interface.ts
src/services/interfaces/printer-file.dto.ts
src/services/interfaces/printer-files.service.interface.ts
src/services/octoprint/octoprint-api.service.ts
src/services/orm/base.interface.ts
src/services/orm/base.service.ts
src/services/print-completion.service.ts
src/services/printer-files.service.ts
src/services/printer.service.ts
src/state/file.cache.ts
src/state/printer-files.store.ts
src/state/printer.cache.ts
test/api/print-completion-controller.test.ts
test/api/printer-files-controller.test.ts
test/application/store/file-cache.test.ts
test/application/store/files-store.test.ts
test/test-server.ts
yarn.lock

In order to bring SQLite into the picture as a database, the fileList property of the MongoDB collection is in the way.
- This PR moves the fileList (with all risks associated) to a separate table.
- It introduces the typeorm dependency

feat: split out fileList from printer model for forward compatibility

---

src/services/printer-files.service.ts
test/application/store/files-store.test.ts

Fixes the mongodb-based version to be up-to-date with the SQLite service which automatically sets the customData field for a printer file, preventing unnecessary database validation errors.

fix: bring both sqlite and mongodb versions up to date

---

.github/workflows/nodejs.yml
.github/workflows/nodejs_mongodb.yml
src/controllers/printer.controller.ts
src/data-source.ts
src/entities/print-completion.entity.ts
src/migrations/1706821653681-DropCorrelationIdCompletion.ts
src/services/interfaces/print-completion.interface.ts
src/services/orm/base.service.ts
src/services/orm/print-completion.service.ts
src/services/orm/printer.service.ts
src/tasks/print-completion.socketio.task.ts
test/api/print-completion-controller.test.ts

Drop the print completion correlation Id as it was required but not available for all code paths.
⚠️ 
In hindsight this is a really, really bad idea. This feature needs to be fixed first.
Now Im listing all the prints in order to find a couple.

fix: drop correlationId from completion table

---

src/controllers/printer.controller.ts
src/state/printer-events.cache.ts
src/tasks/socketio.task.ts

Remove all state.
Attempt at fixing #2194

feat: clear printer events on socket events store for a complete printer refresh

---

src/middleware/authenticate.ts
src/middleware/global.middleware.ts
src/services/authentication/role.service.ts
src/services/interfaces/role-service.interface.ts
src/services/orm/role.service.ts
src/types/express/index.d.ts

Bugfix for the authorization middleware. User role ids were provided instead of role ids, causing wrong role comparison.

fix: wrong middleware user role ids, should be role ids instead

---

docker/Dockerfile
docker/alpha.Dockerfile
docker/test.Dockerfile

Adds `curl` and `ca-certificates` to the fdm monster images.

fix: add curl and ca-certificates for f.e. optional healthcheck 

---

.env.template
CONTRIBUTING.md
RELEASE_NOTES.MD
installations/ansible/playbook-ubuntu22.yaml
src/controllers/server-public.controller.ts
src/services/core/yaml.service.ts
src/services/floor.service.ts
src/services/interfaces/floor.service.interface.ts
src/services/orm/base.interface.ts
src/services/orm/base.service.ts
src/services/orm/floor-position.service.ts
src/services/orm/floor.service.ts
test/api/test-data/create-printer.ts
test/application/test-data/export-fdm-monster-1.5.2-mongodb-simple.yaml
test/application/yaml-service.test.ts
test/setup-after-env.ts

Fix/1948 importing existing printers can clear out floor positions 

---

src/services/orm/floor.service.ts

Without this quick bugfix, import might fail due to printers already existing on a different floor. It's an edge case and its a regression, so this fix ensures that we can wait with issue https://github.com/fdm-monster/fdm-monster/issues/3100

fix: prevent floor position database constraints by removing printer position from any floor beforehand

---

.gitignore
installations/other/octofarm/docker-compose.yml
src/controllers/printer.controller.ts

During the work on https://github.com/fdm-monster/fdm-monster/issues/3073 the issue was mostly on client side https://github.com/fdm-monster/fdm-monster-client/pull/1186
This PR simply adds an OctoFarm docker-compose file for reference and quick testing.

Provide OctoFarm compose for quick tests

---

RELEASE_NOTES.MD
src/services/orm/floor-position.service.ts

This PR fixes the problem described in #3103

fix: deleting a printer position by printer id should not clear a different position

---

src/controllers/auth.controller.ts
src/controllers/server-public.controller.ts
src/middleware/global.middleware.ts
src/tasks/boot.task.ts

When first time setup has not been completed as normal, disabling demo mode can cause the server to be in illegal state: no admin/root user, but also no way to create one.
This PR fixes the demo mode: the first time setting is not touched, and avoided in middleware when in demo mode.

fix: first time setup should not be completed in demo mode

---

RELEASE_NOTES.MD
src/controllers/server-private.controller.ts
src/controllers/server-public.controller.ts
src/exceptions/runtime.exceptions.ts
src/services/core/client-bundle.service.ts
src/services/core/github.service.ts
src/services/octoprint/octoprint-api.service.ts
src/services/octoprint/octoprint-sockio.adapter.ts

Server PR accompanying https://github.com/fdm-monster/fdm-monster-client/pull/1192
See the UI changes here
These are the UI change:
The server improvements:

Feat/2042 handle GitHub api limits in the software upgrade UI

---

.github/workflows/nodejs_release.yml
.npmignore
package.json

The folder `.yarn` was missing which is crucial in combination with `.yarnrc.yml`. Either the rc file has to not specify `yarnPath` or the yarnPath needs to be valid.

fix: add .yarn folder to release zip asset on github

---

.gitignore
RELEASE_NOTES.MD
package.json
src/controllers/server-public.controller.ts
src/controllers/settings.controller.ts
src/controllers/validation/printer-controller.validation.ts
src/middleware/printer.ts
src/server.constants.ts
src/services/core/yaml.service.ts
src/services/moonraker.api.ts
src/services/moonraker/moonraker-websocket.adapter.ts
src/services/moonraker/moonraker.client.ts
src/services/octoprint/dto/octoprint-event.dto.ts
src/services/octoprint/utils/file.utils.ts
src/services/printer-api.factory.ts
src/services/printer-api.interface.ts
src/services/socket.factory.ts
src/services/validators/printer-service.validation.ts
src/services/validators/yaml-service.validation.ts
src/state/printer-events.cache.ts
src/state/printer-files.store.ts
src/state/printer.cache.ts
test/api/printer-controller.test.ts
test/api/settings-controller.test.ts
test/application/store/files-store.test.ts
test/test-server.ts
yarn.lock

Support Moonraker and therefore Klipper

---

RELEASE_NOTES.MD
package.json
src/constants/service.constants.ts
src/controllers/validation/printer-controller.validation.ts
src/models/Printer.ts
src/server.constants.ts
src/services/validators/printer-service.validation.ts
src/services/validators/yaml-service.validation.ts
src/state/validation/create-test-printer.validation.ts
test/api/printer-controller.test.ts
yarn.lock

This was an unexpected breaking change in OctoPrint 1.10.3. This PR fixes #3752

fix: adjust max length of apiKey property validation to 43 to allow new `secrets` based OctoPrint api keys

---

RELEASE_NOTES.MD
src/state/printer-events.cache.ts
src/state/printer.cache.ts
src/state/test-printer-socket.store.ts
src/utils/cache/key-diff.cache.ts

This is a regression and bug that has existed for a while now.
If a printer is deleted, events should not be kept. They should be purged and any update should be rejected.

fix: when printers and test printers are deleted, the printer events cache should not be allowed to be filled by late update events

---

RELEASE_NOTES.MD
src/services/octoprint/octoprint-websocket.adapter.ts

fix: incorrect UI state "No USB" shown, when OctoPrint USB is disconnected

---

RELEASE_NOTES.MD
src/services/moonraker/moonraker-websocket.adapter.ts

fix: sometimes the moonraker services object can miss properties

---

RELEASE_NOTES.MD
src/services/octoprint/octoprint.client.ts

Regression or unintended behavior. Avoids folders in the file list of OctoPrint.

fix: filter folders on calling getLocalFiles for OctoPrint

---

RELEASE_NOTES.MD
package.json
src/consoles/http-file-receiver.console.ts
src/constants/event.constants.ts
src/controllers/printer-files.controller.ts
src/server.constants.ts
src/services/core/multer.service.ts
src/services/interfaces/file-upload-tracker.interface.ts
src/services/moonraker/moonraker.client.ts
src/services/octoprint/octoprint.client.ts
src/shared/default-http-client.builder.ts
src/state/file-upload-tracker.cache.ts
src/tasks/boot.task.ts
src/tasks/socketio.task.ts
test/api/printer-files-controller.test.ts
test/application/multer.service.test.ts
yarn.lock

Fixes #4077.
**Test Configuration**:
* Node version:
* OctoPrint version:
* Klipper version:
* Nodemon/PM2/docker:

fix: upload progress was not reported

---

RELEASE_NOTES.MD
src/controllers/printer-files.controller.ts
src/services/core/logs-manager.service.ts
src/services/core/multer.service.ts
src/services/moonraker/moonraker.client.ts
src/services/octoprint/octoprint.client.ts
src/utils/pretty-print.utils.ts

- Fix Moonraker file upload did not track upload, failure or completion
- Fix Moonraker file upload did not try-catch failures
- Fix thumbnail is now parsed after file upload instead of before, preventing premature thumbnail switch in case of upload failure.
- Fix file uploads were never unlinked, except for server startup.

4086 [Bug]: failed upload still ends up in changed thumbnail

---

RELEASE_NOTES.MD
src/services/moonraker/moonraker.client.ts

When using OctoPrint or PrusaLink we're used to this behaviour, so for consistency it should happen here as well

fix: klipper upload now starts print immediately

---

package.json
src/controllers/server-public.controller.ts
src/server.constants.ts
src/services/moonraker/moonraker-websocket.adapter.ts
src/services/moonraker/moonraker.client.ts
yarn.lock

Fixes #4321 and adds better failure handling on first API call. ECONNREFUSED, ECONNRESET, ETIMEDOUT or EHOSTUNREACH should not result in huge object in the logs.
Locally with a non-existent / down Moonraker API.

Fix/4321 moonraker setup not failure tolerant, verbose error log with whole axios response
